### PR TITLE
[cpw-63] Add top contractors

### PR DESCRIPTION
**Pull request by alex-novak**

### CODE REVIEW

**Comment by albertvolkman** [comment]
The image resolutions looks really low-

Screen Shot 2021-02-17 at 11 42 24 AM

**Comment by alex-novak** [comment]
> The image resolutions looks really low-
> 
> Screen Shot 2021-02-17 at 11 42 24 AM

Changed Top contractors list and photos in the next PR

**Comment by albertvolkman** [comment]
@alex-novak close this PR?

**Comment by alex-novak** [comment]
> @alex-novak close this PR?

yes, we can close this

**Pull request closed without merging**
